### ISSUE TITLE
WhatsApp Web crashed #2

### ISSUE THREAD

**Issue by RiRe** [ninov/watex#28]

**Comment by ninov** [comment]
Can't reproduce. Please add a crash log / stack trace

**Comment by RiRe** [comment]
Open our chat and you can reproduce it.

**Comment by ninov** [comment]
Just a question of available hardware. Try running some EC2 instances with WhatsApp Web.
#29

**Comment by RiRe** [comment]
Can I have your credit card number?

**Comment by ninov** [comment]
Hiermit erteile ich Ihnen virtuelles Hausverbot in dem Github-Repository ninov/watex

Am 18. Januar 2017 16:35:03 MEZ schrieb RiRe <notifications@github.com>:
>Can I have your credit card number?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/ninov/watex/issues/28#issuecomment-273508404

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
